---
- name: My first play
  hosts: tag_Environment_dev:&tag_System_web:&tag_Subsystem_api

  tasks:
    # https://docs.ansible.com/ansible/2.9/modules/ping_module.html#ping-module
    - name: Ping my hosts
      ansible.builtin.ping:
    # https://docs.ansible.com/ansible/latest/collections/ansible/builtin/debug_module.html
    - name: Print message
      ansible.builtin.debug:
        msg: Hello world
    # https://docs.ansible.com/ansible/2.9/modules/service_facts_module.html#service-facts-module
#     - name: Populate service facts
#       service_facts:
#     - debug:
#         var: ansible_facts.services
#     # https://docs.ansible.com/ansible/latest/collections/ansible/builtin/command_module.html
#     - name: Return listing to registered var
#       ansible.builtin.command: ls -alh
#       register: result
#     # https://docs.ansible.com/ansible/latest/collections/ansible/builtin/debug_module.html
#     - name: Print return information from the previous task
#       debug:
#         var: result.stdout_lines

